/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BarberSoftwareAustraliaRouteImport } from './routes/barber-software-australia'
import { Route as BeautySalonSoftwareAustraliaRouteImport } from './routes/beauty-salon-software-australia'
import { Route as CommissionFreeBookingSoftwareRouteImport } from './routes/commission-free-booking-software'
import { Route as GetInTouchRouteImport } from './routes/get-in-touch'
import { Route as HairSalonSoftwareAustraliaRouteImport } from './routes/hair-salon-software-australia'
import { Route as NoMonthlyFeeSalonSoftwareRouteImport } from './routes/no-monthly-fee-salon-software'
import { Route as SalonBookingSoftwareAustraliaRouteImport } from './routes/salon-booking-software-australia'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as FeaturesClientManagementRouteImport } from './routes/features/client-management'
import { Route as FeaturesPaymentsPosRouteImport } from './routes/features/payments-pos'
import { Route as FeaturesRevenueOpportunitiesRouteImport } from './routes/features/revenue-opportunities'
import { Route as LegalIndexRouteImport } from './routes/legal/index'
import { Route as LegalSlugRouteImport } from './routes/legal/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BarberSoftwareAustraliaRoute = BarberSoftwareAustraliaRouteImport.update({
  id: '/barber-software-australia',
  path: '/barber-software-australia',
  getParentRoute: () => rootRouteImport,
} as any)
const BeautySalonSoftwareAustraliaRoute =
  BeautySalonSoftwareAustraliaRouteImport.update({
    id: '/beauty-salon-software-australia',
    path: '/beauty-salon-software-australia',
    getParentRoute: () => rootRouteImport,
  } as any)
const CommissionFreeBookingSoftwareRoute =
  CommissionFreeBookingSoftwareRouteImport.update({
    id: '/commission-free-booking-software',
    path: '/commission-free-booking-software',
    getParentRoute: () => rootRouteImport,
  } as any)
const GetInTouchRoute = GetInTouchRouteImport.update({
  id: '/get-in-touch',
  path: '/get-in-touch',
  getParentRoute: () => rootRouteImport,
} as any)
const HairSalonSoftwareAustraliaRoute =
  HairSalonSoftwareAustraliaRouteImport.update({
    id: '/hair-salon-software-australia',
    path: '/hair-salon-software-australia',
    getParentRoute: () => rootRouteImport,
  } as any)
const NoMonthlyFeeSalonSoftwareRoute =
  NoMonthlyFeeSalonSoftwareRouteImport.update({
    id: '/no-monthly-fee-salon-software',
    path: '/no-monthly-fee-salon-software',
    getParentRoute: () => rootRouteImport,
  } as any)
const SalonBookingSoftwareAustraliaRoute =
  SalonBookingSoftwareAustraliaRouteImport.update({
    id: '/salon-booking-software-australia',
    path: '/salon-booking-software-australia',
    getParentRoute: () => rootRouteImport,
  } as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesClientManagementRoute =
  FeaturesClientManagementRouteImport.update({
    id: '/features/client-management',
    path: '/features/client-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const FeaturesPaymentsPosRoute = FeaturesPaymentsPosRouteImport.update({
  id: '/features/payments-pos',
  path: '/features/payments-pos',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRevenueOpportunitiesRoute =
  FeaturesRevenueOpportunitiesRouteImport.update({
    id: '/features/revenue-opportunities',
    path: '/features/revenue-opportunities',
    getParentRoute: () => rootRouteImport,
  } as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/barber-software-australia': typeof BarberSoftwareAustraliaRoute
  '/beauty-salon-software-australia': typeof BeautySalonSoftwareAustraliaRoute
  '/commission-free-booking-software': typeof CommissionFreeBookingSoftwareRoute
  '/get-in-touch': typeof GetInTouchRoute
  '/hair-salon-software-australia': typeof HairSalonSoftwareAustraliaRoute
  '/no-monthly-fee-salon-software': typeof NoMonthlyFeeSalonSoftwareRoute
  '/salon-booking-software-australia': typeof SalonBookingSoftwareAustraliaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/features/client-management': typeof FeaturesClientManagementRoute
  '/features/payments-pos': typeof FeaturesPaymentsPosRoute
  '/features/revenue-opportunities': typeof FeaturesRevenueOpportunitiesRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/legal/': typeof LegalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/barber-software-australia': typeof BarberSoftwareAustraliaRoute
  '/beauty-salon-software-australia': typeof BeautySalonSoftwareAustraliaRoute
  '/commission-free-booking-software': typeof CommissionFreeBookingSoftwareRoute
  '/get-in-touch': typeof GetInTouchRoute
  '/hair-salon-software-australia': typeof HairSalonSoftwareAustraliaRoute
  '/no-monthly-fee-salon-software': typeof NoMonthlyFeeSalonSoftwareRoute
  '/salon-booking-software-australia': typeof SalonBookingSoftwareAustraliaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/features/client-management': typeof FeaturesClientManagementRoute
  '/features/payments-pos': typeof FeaturesPaymentsPosRoute
  '/features/revenue-opportunities': typeof FeaturesRevenueOpportunitiesRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/blog': typeof BlogIndexRoute
  '/legal': typeof LegalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/barber-software-australia': typeof BarberSoftwareAustraliaRoute
  '/beauty-salon-software-australia': typeof BeautySalonSoftwareAustraliaRoute
  '/commission-free-booking-software': typeof CommissionFreeBookingSoftwareRoute
  '/get-in-touch': typeof GetInTouchRoute
  '/hair-salon-software-australia': typeof HairSalonSoftwareAustraliaRoute
  '/no-monthly-fee-salon-software': typeof NoMonthlyFeeSalonSoftwareRoute
  '/salon-booking-software-australia': typeof SalonBookingSoftwareAustraliaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/features/client-management': typeof FeaturesClientManagementRoute
  '/features/payments-pos': typeof FeaturesPaymentsPosRoute
  '/features/revenue-opportunities': typeof FeaturesRevenueOpportunitiesRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/legal/': typeof LegalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/barber-software-australia'
    | '/beauty-salon-software-australia'
    | '/commission-free-booking-software'
    | '/get-in-touch'
    | '/hair-salon-software-australia'
    | '/no-monthly-fee-salon-software'
    | '/salon-booking-software-australia'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/features/client-management'
    | '/features/payments-pos'
    | '/features/revenue-opportunities'
    | '/legal/$slug'
    | '/blog/'
    | '/legal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/barber-software-australia'
    | '/beauty-salon-software-australia'
    | '/commission-free-booking-software'
    | '/get-in-touch'
    | '/hair-salon-software-australia'
    | '/no-monthly-fee-salon-software'
    | '/salon-booking-software-australia'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/features/client-management'
    | '/features/payments-pos'
    | '/features/revenue-opportunities'
    | '/legal/$slug'
    | '/blog'
    | '/legal'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/barber-software-australia'
    | '/beauty-salon-software-australia'
    | '/commission-free-booking-software'
    | '/get-in-touch'
    | '/hair-salon-software-australia'
    | '/no-monthly-fee-salon-software'
    | '/salon-booking-software-australia'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/features/client-management'
    | '/features/payments-pos'
    | '/features/revenue-opportunities'
    | '/legal/$slug'
    | '/blog/'
    | '/legal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BarberSoftwareAustraliaRoute: typeof BarberSoftwareAustraliaRoute
  BeautySalonSoftwareAustraliaRoute: typeof BeautySalonSoftwareAustraliaRoute
  CommissionFreeBookingSoftwareRoute: typeof CommissionFreeBookingSoftwareRoute
  GetInTouchRoute: typeof GetInTouchRoute
  HairSalonSoftwareAustraliaRoute: typeof HairSalonSoftwareAustraliaRoute
  NoMonthlyFeeSalonSoftwareRoute: typeof NoMonthlyFeeSalonSoftwareRoute
  SalonBookingSoftwareAustraliaRoute: typeof SalonBookingSoftwareAustraliaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogSlugRoute: typeof BlogSlugRoute
  FeaturesClientManagementRoute: typeof FeaturesClientManagementRoute
  FeaturesPaymentsPosRoute: typeof FeaturesPaymentsPosRoute
  FeaturesRevenueOpportunitiesRoute: typeof FeaturesRevenueOpportunitiesRoute
  LegalSlugRoute: typeof LegalSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  LegalIndexRoute: typeof LegalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barber-software-australia': {
      id: '/barber-software-australia'
      path: '/barber-software-australia'
      fullPath: '/barber-software-australia'
      preLoaderRoute: typeof BarberSoftwareAustraliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beauty-salon-software-australia': {
      id: '/beauty-salon-software-australia'
      path: '/beauty-salon-software-australia'
      fullPath: '/beauty-salon-software-australia'
      preLoaderRoute: typeof BeautySalonSoftwareAustraliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commission-free-booking-software': {
      id: '/commission-free-booking-software'
      path: '/commission-free-booking-software'
      fullPath: '/commission-free-booking-software'
      preLoaderRoute: typeof CommissionFreeBookingSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-in-touch': {
      id: '/get-in-touch'
      path: '/get-in-touch'
      fullPath: '/get-in-touch'
      preLoaderRoute: typeof GetInTouchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hair-salon-software-australia': {
      id: '/hair-salon-software-australia'
      path: '/hair-salon-software-australia'
      fullPath: '/hair-salon-software-australia'
      preLoaderRoute: typeof HairSalonSoftwareAustraliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-monthly-fee-salon-software': {
      id: '/no-monthly-fee-salon-software'
      path: '/no-monthly-fee-salon-software'
      fullPath: '/no-monthly-fee-salon-software'
      preLoaderRoute: typeof NoMonthlyFeeSalonSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salon-booking-software-australia': {
      id: '/salon-booking-software-australia'
      path: '/salon-booking-software-australia'
      fullPath: '/salon-booking-software-australia'
      preLoaderRoute: typeof SalonBookingSoftwareAustraliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/client-management': {
      id: '/features/client-management'
      path: '/features/client-management'
      fullPath: '/features/client-management'
      preLoaderRoute: typeof FeaturesClientManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/payments-pos': {
      id: '/features/payments-pos'
      path: '/features/payments-pos'
      fullPath: '/features/payments-pos'
      preLoaderRoute: typeof FeaturesPaymentsPosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/revenue-opportunities': {
      id: '/features/revenue-opportunities'
      path: '/features/revenue-opportunities'
      fullPath: '/features/revenue-opportunities'
      preLoaderRoute: typeof FeaturesRevenueOpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/': {
      id: '/legal/'
      path: '/legal'
      fullPath: '/legal/'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$slug': {
      id: '/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BarberSoftwareAustraliaRoute: BarberSoftwareAustraliaRoute,
  BeautySalonSoftwareAustraliaRoute: BeautySalonSoftwareAustraliaRoute,
  CommissionFreeBookingSoftwareRoute: CommissionFreeBookingSoftwareRoute,
  GetInTouchRoute: GetInTouchRoute,
  HairSalonSoftwareAustraliaRoute: HairSalonSoftwareAustraliaRoute,
  NoMonthlyFeeSalonSoftwareRoute: NoMonthlyFeeSalonSoftwareRoute,
  SalonBookingSoftwareAustraliaRoute: SalonBookingSoftwareAustraliaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogSlugRoute: BlogSlugRoute,
  FeaturesClientManagementRoute: FeaturesClientManagementRoute,
  FeaturesPaymentsPosRoute: FeaturesPaymentsPosRoute,
  FeaturesRevenueOpportunitiesRoute: FeaturesRevenueOpportunitiesRoute,
  LegalSlugRoute: LegalSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  LegalIndexRoute: LegalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
